baseURL = 'https://sccrosby.github.io'
languageCode = 'en-us'
title = 'Sean C. Crosby'
theme = 'hugo-theme-cleanwhite'
paginate = 5000 #frontpage pagination

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  #header_image = "images/main_go_wideandtall_darklayer.jpeg"
  header_image = "/img/islands.jpg"
  title = "Software Engineering"
  slogan = "\"All models are wrong, some are useful\" -George Box"
  SEOTitle = "Sean C. Crosby Blog"
  keyword = "Python, Matlab, SQL, , Raspberry, Pi, Docker, Kubernetes, Go, Golang, Microservice"
 
  # Sidebar settings
  sidebar_about_description = "Father, Partner, Runner, Kitefoiler, Scientist"
  sidebar_avatar = "/img/me.jpg"
  about_me = true

  featured_tags = true 
  featured_condition_size = 2 # How many posts have to have a given tag to be featured (greater-than)

  image_404 = "images/404-bg.jpg"
  title_404 = "We couldn't find what you were looking for..."

  omit_categories = true

  [[params.addtional_menus]]
  title =  "About"
  href =  "/top/about/"

  [[params.addtional_menus]]
  title =  "Academic Research"
  href =  "/top/research/"

  [params.social]
  rss            = true
  email          = "schcrosby@gmail.com"
  linkedin       = "https://www.linkedin.com/in/seanchcrosby/"
  github         = "https://github.com/sccrosby"
  #medium         = "https://medium.com/@RichYoungkin"
  #stackoverflow  = "https://stackoverflow.com/users/2646870/rich"
  #reddit         = "https://www.reddit.com/user/elevation5280"
